url: "http://magokoro.akixuu.ca/" 
baseurl: ""
title: "Magokoro Wellness"
description: "Magokoro Wellness Team official website"

plugins:
  - jekyll-loading-lazy
  - jekyll-sass-converter
  

theme: null

contact:
  phone: 6043128883
  email: magokorowellnessteam@gmail.com 

defaults:
-
    scope:
      path: ""
      type: "pages"
    values:
      layout: "wrapper"
