url: "http://magokoro.com" 
baseurl: ""
title: "Magokoro Wellness"
description: ""

plugins:
  - jekyll-loading-lazy

contact:
  phone: 6043128883
  email: magokorowellnessteam@gmail.com 

defaults:
-
    scope:
      path: ""
      type: "pages"
    values:
      layout: "wrapper"